### ISSUE TITLE
home page font-size responsiveness

### ISSUE THREAD

**Issue by Anubhav-kaushik** [Anubhav-kaushik/godspeed-visualbest#1]
"Hi @Shikha, the client has asked that we add the Salesforce logo to all of the ads since it is a cobranded campaign.

We also need to update all of the copy so that it is in sentence format. Meaning only the first letter of the first word is capitalized at the beginning of each sentence. But the CTAs can stay the same. So they should look the same as below

Life Sciences
""Higher operational efficiency. Better patient communications. Less cost.""
CTA = Grow My Pipeline

Healthcare
""More satisfied providers. Less paperwork. More time for patient Care.
CTA = Get Started

J&J
This one is already in Sentence case but we just need to add the Salesforce logo to them please

Please let me know if you have any questions or need anything else from me

Thank you for your help!"

**Comment by Anubhav-kaushik** [comment]
working

**Comment by codingclap** [comment]
Ok
